const express = require("express")
const router = express.Router()
const methodOvveride = require("method-override")
const controller = require("../controllers/myPage")
router.use(methodOvveride("_method"))
router.get("/myPage/:id", controller.getMyPage)
router.get("/myPage/profile/:id", controller.getProfile)
router.put("/myPage/profile/:id", controller.updateUser)
router.get("/myPage/messages", controller.getMessages)
router.get("/myPage/messages/newMessage", controller.getNewMessage)
router.post("/mypage/messages/newMessage", controller.newMessage)
router.get("/myPage/messages/:id", controller.getOneMessage)
router.delete("/myPage/messages/:id",controller.deleteOneMessage)
router.get("/myPage/messages/messagesSend", controller.getMessagesSend)
router.get("/myPage/messages/messagesGot", controller.getMessagesGot)
router.get("/myPage/myRequests:id", controller.getMyRequests)
router.delete("/myPage/myRequests/:id", controller.deleteRequest)
router.get("/myPage/myRequests/:id", controller.getUpdateRequest)
router.put("/myPage/myRequests/:id", controller.updateRequest)
router.get("/myPage/myRequests/newRequest", controller.getNewRequest)
router.post("/myPage/myRequests/newRequest", controller.newRequest)
module.exports = router