const express = require("express")
const router = express.Router()
const methodOvveride = require("method-override")
const controller = require("../controllers/myPage")
const passport = require("passport")
const multer  = require("multer")
const upload = require("../middleware/loadAny")
const urlencodedParser = express.urlencoded({extended: false});

router.use(methodOvveride("_method"))
 
router.get("/", passport.authenticate('jwt', {session:false}), controller.getMyPage)
router.get("/profile", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getProfile)
router.put("/profile", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.updateUser)
router.get("/messages/newMessage", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getNewMessage)
router.post("/messages/newMessage", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), upload.single("any"), controller.newMessage)
router.get("/messages/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getOneMessage)
router.delete("/messages/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.deleteOneMessage)
router.get("/messages", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getMessages)
router.get("/myRequests", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getMyRequests)
router.get("/myRequests/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getMyRequests)
router.delete("/myRequests/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.deleteRequest)
router.get("/myRequests/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getUpdateRequest)
router.put("/myRequests/:id", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.updateRequest)
router.get("/myRequests/newRequest", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.getNewRequest)
router.post("/myRequests/newRequest", passport.authenticate('jwt', {session:false, failureRedirect: "/api/auth/login"}), controller.newRequest)
module.exports = router